- name: Manage DBs for BAN
  include_tasks: db/ban.yml

- name: Manage DBs for BAS
  include_tasks: db/bas.yml
  when: current_cp4ba_cluster.cp4ba.patterns.foundation.optional_components.bas

- name: Manage DBs for ODM
  include_tasks: db/odm.yml
  when: current_cp4ba_cluster.cp4ba.patterns.decisions.enabled

- name: Manage DBs for FNCM
  include_tasks: db/fncm.yml
  when: current_cp4ba_cluster.cp4ba.patterns.content.enabled

- name: Manage DBs for IER
  include_tasks: db/ier.yml
  when: current_cp4ba_cluster.cp4ba.patterns.content.enabled and current_cp4ba_cluster.cp4ba.patterns.content.optional_components.ier

- name: Manage DBs for AAE
  include_tasks: db/aae.yml
  when: current_cp4ba_cluster.cp4ba.patterns.application.enabled

- name: Manage DBs for AAE Data persistence
  include_tasks: db/aae-data-persistence.yml
  when: current_cp4ba_cluster.cp4ba.patterns.application.enabled and current_cp4ba_cluster.cp4ba.patterns.application.optional_components.ae_data_persistence

- name: Manage DBs for ADP
  include_tasks: db/adp.yml
  when: current_cp4ba_cluster.cp4ba.patterns.document_processing.enabled

- name: Manage DBs for BAWAUT
  include_tasks: db/bawaut.yml
  when: current_cp4ba_cluster.cp4ba.patterns.workflow.enabled and current_cp4ba_cluster.cp4ba.patterns.workflow.optional_components.baw_authoring
